### ISSUE TITLE
Use @data-testid instead of verbose xPaths

### ISSUE THREAD

**Issue by Charlignon** [EKOzkan/twAuto#1]
Hey ! Thank you so much for making this client ! This will help me circumvent the Twitter API ban and keep my bot alive :)
I played a bit with it in order to make it work on Linux and tweak it to my needs.

One things noticed is that some selectors are not working properly : unfortunately, Twitter has a habit of breaking their dom structure and class ids. I suggest you use selectors based on the `data-testid` field, which is pretty reliable in the long term, you should be able to avoid most breaking changes with it. Example :
```python
                body_element = container_element.find_element(XPATH, './/div[3]/div[7]/div/div[2]/div')
```
became
```python
                body_element = container_element.find_element(XPATH, '//*[@data-testid="retweet"]')
```

Don't know if this is related to this change, but `body_element.click()` would not work afterward, so I used `twAuto.driver.execute_script("arguments[0].click()", body_element)` instead.

Glad I found your project ! Thanks again for your work :)

**Comment by EKOzkan** [comment]
I am so glad that it helped your work. Twitter UI keeps getting updated after recent changes, so I was waiting for the UI redesign to finalize before updating the lib. I didn't aware of the "data-testid" solution. Thank you for pointing it out. I will try to update the project as soon as possible based on this method.

**Comment by EKOzkan** [comment]
I am so glad that it helped your work. Twitter UI keeps getting updated after recent changes, so I was waiting for the UI redesign to finalize before updating the lib. I wasn't aware of the "data-testid" solution. So thank you for pointing it out. I will try to update the project as soon as possible based on this method.

**Comment by Concept211** [comment]
Looking forward to some updates on this because right now it's not working at all. Twitter changed their login to only display the Username field first and then asking for Password on the next screen (pita) 🙄

**Comment by EKOzkan** [comment]
Lib should still work with that. Are you working on Linux?

> Looking forward to some updates on this because right now it's not working at all. Twitter changed their login to only display the Username field first and then asking for Password on the next screen (pita) 🙄

**Comment by Concept211** [comment]
> Lib should still work with that. Are you working on Linux?
> 
> > Looking forward to some updates on this because right now it's not working at all. Twitter changed their login to only display the Username field first and then asking for Password on the next screen (pita) 🙄

No, I'm on Windows. I turned off headless so that I can watch the login process but it only fills in the username field and then errors out since there's no Password field on the new login screen.
![image](https://user-images.githubusercontent.com/589002/219898892-cfa3e8c8-451d-476a-965c-37a6e2e45031.png)

**Comment by EKOzkan** [comment]
Ok can you share your code with me, dont forget to delete your username, password and email infos, because lib already works with this situation, I have just tried it.

> > Lib should still work with that. Are you working on Linux?
> > > Looking forward to some updates on this because right now it's not working at all. Twitter changed their login to only display the Username field first and then asking for Password on the next screen (pita) 🙄
> 
> No, I'm on Windows. I turned off headless so that I can watch the login process but it only fills in the username field and then errors out since there's no Password field on the new login screen. ![image](https://user-images.githubusercontent.com/589002/219898892-cfa3e8c8-451d-476a-965c-37a6e2e45031.png)

**Comment by EKOzkan** [comment]
> > Lib should still work with that. Are you working on Linux?
> > > Looking forward to some updates on this because right now it's not working at all. Twitter changed their login to only display the Username field first and then asking for Password on the next screen (pita) 🙄
> 
> No, I'm on Windows. I turned off headless so that I can watch the login process but it only fills in the username field and then errors out since there's no Password field on the new login screen. ![image](https://user-images.githubusercontent.com/589002/219898892-cfa3e8c8-451d-476a-965c-37a6e2e45031.png)

Ok can you share your code with me, dont forget to delete your username, password and email infos, because lib already works with this situation, I have just tried it.

**Comment by Concept211** [comment]
I actually simply used your code from your readme to test like...

```
import twAuto

tw = twAuto.twAuto(
username="Username",
email="email@isp.com",
password="Pass123",
headless=False)

tw.start()
tw.login()

tw.tweet(text="Hello World",imgpath="")

tw.logout()
close()
```

**Comment by EKOzkan** [comment]
Added data-testid mode and manual and automatic driver modes in the new version.
4da611d9e856cf07bb49a0ee42fb9e67b0364fd1

**Comment by Concept211** [comment]
Thanks for the update!

So now it seems to log in just fine and even gets to the "Compose Tweet" page/form, fills in the text but now it fails in what it looks like is when it attempts to click the submit button.

The odd thing is that the error mentions that the `text` argument is empty, but it's actually not and it fills in the text successfully. It just fails to submit the form and closes out the chrome instance.

![image](https://user-images.githubusercontent.com/589002/220285833-94bacd5d-a06e-4699-82cd-54adb6e4909b.png)

**Comment by EKOzkan** [comment]
If you are not going to use the imgpath do not include it in the parameter field, or you can pass None instead of empty string. So this should be fine:
```python
tw.tweet(text="Hello")
```

Thank you for using the lib btw, your feedback really helps me finding these bugs.

**Comment by Concept211** [comment]
That did the trick! 🤦‍♂️ - thank you!
