### ISSUE TITLE
Contribution

### ISSUE THREAD

**Issue by newpolygons** [EKOzkan/twAuto#10]
Hello, Is this project open to contributions? If so how would you like this done.

Thank you

**Comment by EKOzkan** [comment]
Sure, I just added a [Contribution Guide](https://github.com/EKOzkan/twAuto/blob/master/CONTRIBUTING.md). Please don't forget to take a look at the [Notes for Contributors](https://github.com/EKOzkan/twAuto/blob/master/CONTRIBUTING.md#notes-for-contributors). 

Thanks for taking the time to contribute!
