### ISSUE TITLE
Add config to set your own path for the Chromedriver.exe

### ISSUE THREAD

**Issue by Concept211** [EKOzkan/twAuto#2]
I always have my chromedriver.exe in a single location on my server for multiple applications to use the same executable. It would be helpful to add an extra config to allow us to specify a path to it instead of forcing to place it in the same dir as the script. 👍

**Comment by EKOzkan** [comment]
You can now specify driver path in the [v0.3.4](4da611d9e856cf07bb49a0ee42fb9e67b0364fd1)

**Comment by EKOzkan** [comment]
You can now specify driver path in the version 0.3.4. 4da611d9e856cf07bb49a0ee42fb9e67b0364fd1

**Comment by Concept211** [comment]
Awesome! Thanks @EKOzkan 🤝
