### ISSUE TITLE
Can't send text with emojis (ChromeDriver only supports characters in the BMP)

### ISSUE THREAD

**Issue by Concept211** [EKOzkan/twAuto#4]
So there's a known issue where the ChromeDriver isn't able to send emojis via keys. 

![image](https://user-images.githubusercontent.com/589002/220448933-b3d3a892-7583-4353-86db-c457ff6295fa.png)

The workaround is to either use the Firefox driver instead...

Or better yet, someone came up with a solution to copy the emoji text to the clipboard and then paste it into the field while still using Chrome. Below is the SO link with the sample code. I think it would be really useful to implement into twAuto 👌 

https://stackoverflow.com/a/72473110/617909

**Comment by EKOzkan** [comment]
Added emoji support to reply and tweet functions in v0.3.6. 0f2333d718d0e4e5a978dafc748743df4a8fce50
