### ISSUE TITLE
cannot tweet image (linux)

### ISSUE THREAD

**Issue by dmnfarrell** [EKOzkan/twAuto#5]
Tried this on linux and can tweet text ok, but if I try to also tweet an image it gives me this error:
```
twAuto Error:  Message: element click intercepted: Element <div role="button" tabindex="0" class="css-18t94o4 css-1dbjc4n r-l5o3uw r-42olwf r-sdzlij r-1phboty r-rs99b7 r-19u6a5r r-2yi16 r-1qi8awa r-1ny4l3l r-ymttw5 r-o7ynqc r-6416eg r-lrvibr" data-testid="tweetButton">...</div> is not clickable at point (871, 818). Other element would receive the click: <div class="css-1dbjc4n r-1p0dtai r-1d2f490 r-1xcajam r-zchlnj r-ipm5af"></div>
  (Session info: chrome=110.0.5481.177)
```
When I try with headless = False I can see the image has been uploaded into the page but it seems to fail at the last step of pressing the tweet button. Any idea what could be causing this?

**Comment by EKOzkan** [comment]
Can you share your configurations. Don't forget to delete your username, password and email from it tho.

**Comment by dmnfarrell** [comment]
The code is nothing special. img is a valid image path and like I said it is being uploaded to the page. I tried increasing the wait time in part of your code but not sure if that matters.
```
tw = twAuto(
                username=xx,
                email=xx,
                password=xx,
                headless=False,  debugMode= True)
tw.start()
tw.login()
tweetUrl = tw.tweet(text=text, imgpath=img)
```

**Comment by dmnfarrell** [comment]
It just occurred to me to remove the hashtag from the text and now it works without that! Putting a hash anywhere in the text seems to prevent the final click. Could that be fixed? Thanks.

**Comment by EKOzkan** [comment]
Ok, there was a mistake in the documentation, pathType is not "testId" by default. It is "xPath" by default. So probably this change will fix your problem:

```
tw = twAuto.twAuto(
username=xx,
email=xx,
password=xx,
headless=False,
debugMode=True,
pathType="testId")
```

**Comment by dmnfarrell** [comment]
This works now, thank you.
