### ISSUE TITLE
when try tw.start(), errors occured(after try getting cookies manually)

### ISSUE THREAD

**Issue by billbird666** [EKOzkan/twAuto#6]
the error :"//*[@id='layers']/div/div/div/div/div/div/div[2]/div[2]/div/div/div[2]/div[2]/div[1]/div/div/div[3]/div/label/div/div[2]/div[1]/input"

is it because the twitter login page changed?

my code below:

tw = twAuto.twAuto(...
 chromeDriverMode="auto",
driverPath=...,
pathType="testId",
headless=True, 
debugMode= True)

tw.start()

**Comment by EKOzkan** [comment]
I just tried it, and it didn't give me any errors. Changes in the login page shouldn't cause any errors if you created your cookies manually. Can you please check these steps to be sure?

For manual cookie creation, you must fallow these steps:
1- First, you need to add the tw.manualCookieCreation() line after the tw.start() line in your script. Here is an example code snippet:

```import twAuto

tw = twAuto.twAuto(
username="...",
email="...",
password="...",
headless=False,
chromeDriverMode="auto",
debugMode=True,
pathType="testId")

tw.start()
tw.manualCookieCreation()
```
2- Then you run your code, a new Chrome window will open and load the Twitter login page. Log in to your account as usual by entering your email or username and password.

3- After logging in successfully, switch back to the terminal window where you ran your code and press Enter to save the cookies to your current location. The cookie file should be saved as "cookies.pkl". You can confirm that the file was created by checking your folder.

4- Once the cookies have been created, you can terminate the program by pressing Ctrl+C on Windows in your terminal. Finally, remove the tw.manualCookieCreation() line from your code and run it again. The program will use the manually created cookies for the Twitter automation.

**Comment by billbird666** [comment]
now is ok. the issue is that I didn't update the anaconda.
and follow your detailed instruction now I login in sucessfully!
thank you!
