### ISSUE TITLE
 tw.reply(url=  dont work

### ISSUE THREAD

**Issue by benben18273** [EKOzkan/twAuto#7]
tw.reply(url=
 dont work only open page and close it 
tryed to add sleep time but didnt work

**Comment by EKOzkan** [comment]
> Hi, can you share your code please?

**Comment by benben18273** [comment]
yes
from asyncio import sleep
import time
import twAuto
tw = twAuto.twAuto(
  username="",
  email="",
  password="",
  headless=True,
  chromeDriverMode="auto",
  pathType="testId",
  debugMode= True)


tw.start()
tw.login()
tweet = tw.retweet(url="")

replyURL = tw.reply(url="https://twitter.com/Account name /status/id", text="My text")
print(tw.reply);
time.sleep(39);
print(replyURL);
tw.logout()

tw.close()

**Comment by benben18273** [comment]
Reetweet Like and tweet work fine only reply doeesnt work

**Comment by benben18273** [comment]
the debug is 

twAuto started.
Succesfully Logged In
This account already retweeted this tweet.
False
twAuto Error:  Message: invalid argument
  (Session info: headless chrome=113.0.5672.127)
Stacktrace:
Backtrace:
        GetHandleVerifier [0x00A18893+48451]
        (No symbol) [0x009AB8A1]
        (No symbol) [0x008B4F20]
        (No symbol) [0x008A8702]
        (No symbol) [0x008A6F58]
        (No symbol) [0x008A74A8]
        (No symbol) [0x008B67F2]
        (No symbol) [0x0090CA61]
        (No symbol) [0x008FA2BC]
        (No symbol) [0x0090C482]
        (No symbol) [0x008FA0B6]
        (No symbol) [0x008D7E08]
        (No symbol) [0x008D8F2D]
        GetHandleVerifier [0x00C78E3A+2540266]
        GetHandleVerifier [0x00CB8959+2801161]
        GetHandleVerifier [0x00CB295C+2776588]
        GetHandleVerifier [0x00AA2280+612144]
        (No symbol) [0x009B4F6C]
        (No symbol) [0x009B11D8]
        (No symbol) [0x009B12BB]
        (No symbol) [0x009A4857]
        BaseThreadInitThunk [0x758D6739+25]
        RtlGetFullPathName_UEx [0x77B58ACF+1215]
        RtlGetFullPathName_UEx [0x77B58A9D+1165]

<bound method twAuto.reply of <twAuto.twauto.twAuto object at 0x000001B387768790>>
False

**Comment by EKOzkan** [comment]
Hi again, thanks for the feedback. I inspected this problem and found out that twitter changed their HTML structure. I updated the code, now "reply" function relies on the testIds, so that it will going to affect less from the HTML structure changes.  c1a9ae17f8115505c190733f1ccdd7ec74b33e4b

Can you please update twAuto and check if your problem is fixed. You can update it by using

```pip install twAuto --upgrade```

or

```pip install twAuto==0.3.5```


And in your code, it's probably a typo, print(tw.reply) must be print(replyURL), so this should work fine after the update:
```import time
import twAuto
tw = twAuto.twAuto(
  username="",
  email="",
  password="",
  headless=True,
  chromeDriverMode="auto",
  pathType="testId",
  debugMode= True)

tw.start()
tw.login()
tweet = tw.retweet(url="...")

replyURL = tw.reply(url="...", text="...")
print(replyURL);
tw.logout()

tw.close()

**Comment by benben18273** [comment]
i downloaded the project again and now its working fine thanks
