### ISSUE TITLE
 twAuto.driver.get - AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by kato0232** [EKOzkan/twAuto#8]
Hello there,

I've been using twAuto for some months now and It was working perfectly, however I'm bumping my head against a wall since I reainstalled my OS (W10 2H22)
Basically since 3 days ago I'm getting this same error:

C:\Users\TwitterCookies>py cookiecreator.py
Traceback (most recent call last):
  File "C:\Users\...\cookiecreator.py", line 13, in <module>
    tw.manualCookieCreation()
  File "C:\Users\...\Python311\Lib\site-packages\twAuto\twauto.py", line 145, in manualCookieCreation
    twAuto.driver.get("https://twitter.com/login")
    ^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'

I have tried to run it in other devices, same thing,
tried uninstalling and reinstalling several different versions of python, chrome and chromedrivers, same with selenium and the other dependencies. I'm out of ideas, even checked all the posible solutions chatGPT offered and unsurprisingly didn't changed a thing in the end results.

AttributeError: 'NoneType' object has no attribute 'get'
![image](https://github.com/EKOzkan/twAuto/assets/122095776/1f9d67e8-227f-480a-a3a4-f5a5116f3054)
my twAuto version is the latest
Chrome is up to date
Version 114.0.5735.134 (Official Build) (64-bit)
Python 3.11 (64-bit)

I'm out of ideas. Tried in Linux Ubuntu 22.04.2  too, same error. 
AttributeError: 'NoneType' object has no attribute 'get'

**Comment by EKOzkan** [comment]
Can you provide me your code please.

**Comment by kato0232** [comment]
> Can you provide me your code please.

Yes, sorry, here it is:

import twAuto

tw = twAuto.twAuto(
  username="Your Twitter Username",
  email="Your Twitter E-Mail",
  password="Your Twitter Password",
  chromeDriverMode="auto",
  pathType="xPath",
  headless=False,
)

tw.start()
tw.manualCookieCreation()


Thanks a lot for taking the time!

**Comment by EKOzkan** [comment]
Your code works flawlessly in my setup. The error you got is caused because library cant be able to start the chrome instance. If you enable the debugMode you may be able to get hints about the problem. Can you try this:


```
import twAuto

tw = twAuto.twAuto(
username="Your Twitter Username",
email="Your Twitter E-Mail",
password="Your Twitter Password",
chromeDriverMode="auto",
pathType="xPath",
headless=False,
debugMode=True,
)

tw.start()
tw.manualCookieCreation()

```

**Comment by kato0232** [comment]
Unfortunately I have never gotten any other error than that.
It's weird because it happens in all of my virtual machines too as I mentiones, Win10 for example, if you install Win10, install python, install chrome and pip install the twAuto it will still give this error, 
It must be some package I'm missing that you guys have and I myself had before the windows resintalation-

here is a picture of the debugger to true
![image](https://github.com/EKOzkan/twAuto/assets/122095776/0fd57dcc-a552-4666-b4ef-64f6eeb9be69)

**Comment by EKOzkan** [comment]
Actually, you encountered a different error this time:
![image](https://github.com/EKOzkan/twAuto/assets/44098870/c5dbedd8-db89-4793-8609-79ab133083aa)

The error seems to be caused by the updates in the new Selenium versions. I will update twAuto to be compatible with the newest Selenium version in the future. However, for now, you can try downgrading your Selenium version to either 4.4.3 or 4.5.0. I will provide an update regarding this issue when I implement the update for twAuto to support the latest Selenium version.

To downgrade your Selenium version, you can use the following commands:

First:
`pip uninstall selenium`

Then:
`pip install selenium==4.5.0`

or

`pip install selenium==4.4.3`

Please don't forget to inform me, if that solution solved your problems.

**Comment by kato0232** [comment]
Hi there, it worked, it seems to need selenium 4.4.3 to work tho

Huge thank you!
Great code you have there by the way, keep it up!
