### ISSUE TITLE
getting errors while tw.login()

### ISSUE THREAD

**Issue by pikachu62** [EKOzkan/twAuto#9]
twAuto Error:  Message: Service /data/user/0/ru.iiec.pydroid3/app_HOME/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 1

**Comment by EKOzkan** [comment]
I think you or your system closed the Chrome window automatically. Can you provide me your code please.

**Comment by EKOzkan** [comment]
Ok I just checked the error you provided, are you using an Android device and a Python interpreter to use the library? If thats the case, I have never tried twAuto or any kind of automation in Android devices. But if you provide your code (don't forget to hide your login information in the code you share) I would gladly try to help you about that. If thats not the case, I think you or your system closed the Chrome window automatically, so I still need the code to identify the problem.

**Comment by pikachu62** [comment]
> Ok I just checked the error you provided, are you using an Android device and a Python interpreter to use the library? If thats the case, I have never tried twAuto or any kind of automation in Android devices. But if you provide your code (don't forget to hide your login information in the code you share) I would gladly try to help you about that. If thats not the case, I think you or your system closed the Chrome window automatically, so I still need the code to identify the problem.

Yes, I'm using an Android device (only for testing the code, later I'll move it to a server, if it works)

And this is the code, 

========

import twAuto

tw = twAuto.twAuto(
  username="hidden",
  email="hidden",
  password="hidden",
  chromeDriverMode="auto",
  pathType="testId", 
  headless=True,
  debugMode=True,
)
tw.start()
tw.login()

**Comment by EKOzkan** [comment]
Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it. 

Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.

**Comment by pikachu62** [comment]
> Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it.
> 
> Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.

Okay! I'll once again test it in on my server and will notify you!
Btw, I have a doubt.
Is it good to store the cookie, or to login once everytime the server restarts?

**Comment by EKOzkan** [comment]
The reason behind the cookie storing is, if you don't use it, Twitter will send a notification on every login. If that's not a problem in your case, you can just use the logout function after your processes finished to delete your cookie file.

**Comment by pikachu62** [comment]
> Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it.
> 
> Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.

Same error while doing it in server (used heroku this time)

tw.tweet(text=drunk,imgpath=new_path)
2023-06-28T19:33:59.001361+00:00 app[worker.1]:   File "/usr/local/lib/python3.8/dist-packages/twAuto/twauto.py", line 156, in tweet
2023-06-28T19:33:59.001362+00:00 app[worker.1]:     twAuto.driver.get("https://twitter.com/home")
2023-06-28T19:33:59.001362+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'get'

**Comment by EKOzkan** [comment]
> > Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it.
> > Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.
> 
> Same error while doing it in server (used heroku this time)
> 
> tw.tweet(text=drunk,imgpath=new_path) 2023-06-28T19:33:59.001361+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/twAuto/twauto.py", line 156, in tweet 2023-06-28T19:33:59.001362+00:00 app[worker.1]: twAuto.driver.get("https://twitter.com/home") 2023-06-28T19:33:59.001362+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'get'



Can you try this fix: https://github.com/EKOzkan/twAuto/issues/8#issuecomment-1604698617

Version 4.4.3 solved the same error for that case. And if it does not solves your problem, try enabling the [debug mode](https://github.com/EKOzkan/twAuto#:~:text=debugMode%3D%20True/False), maybe that can gives us more details about your problem.

**Comment by EKOzkan** [comment]
Ok, I made the cookie creation optional in the new release([v0.3.9](https://pypi.org/project/twAuto/0.3.9/)). You can use the [createCookies=False](https://github.com/EKOzkan/twAuto#:~:text=createCookies%3D%20True/False%20%23True%20by%20default.) in the setup to not to create an any cookie file.

**Comment by EKOzkan** [comment]
> > Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it.
> > Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.
> 
> Okay! I'll once again test it in on my server and will notify you! Btw, I have a doubt. Is it good to store the cookie, or to login once everytime the server restarts?

Ok, I made the cookie creation optional in the new release([v0.3.9](https://pypi.org/project/twAuto/0.3.9/)). You can use the [createCookies=False](https://github.com/EKOzkan/twAuto#:~:text=createCookies%3D%20True/False%20%23True%20by%20default.) in the setup to not to create an any cookie file.

**Comment by pikachu62** [comment]
> > > Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it.
> > > Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.
> > 
> > 
> > Same error while doing it in server (used heroku this time)
> > tw.tweet(text=drunk,imgpath=new_path) 2023-06-28T19:33:59.001361+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/twAuto/twauto.py", line 156, in tweet 2023-06-28T19:33:59.001362+00:00 app[worker.1]: twAuto.driver.get("https://twitter.com/home") 2023-06-28T19:33:59.001362+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'get'
> 
> Can you try this fix: [#8 (comment)](https://github.com/EKOzkan/twAuto/issues/8#issuecomment-1604698617)
> 
> Version 4.4.3 solved the same error for that case. And if it does not solves your problem, try enabling the [debug mode](https://github.com/EKOzkan/twAuto#:~:text=debugMode%3D%20True/False), maybe that can gives us more details about your problem.

Actually, I enabled debug mode, there is nothing in the heroku logs
And previously, when I used Android, this is the same error which occured but additionally got a debug log, which I showed you at the start.
But this time there is no debug log in heroku logs.

**Comment by EKOzkan** [comment]
> > > > Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it.
> > > > Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.
> > > 
> > > 
> > > Same error while doing it in server (used heroku this time)
> > > tw.tweet(text=drunk,imgpath=new_path) 2023-06-28T19:33:59.001361+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/twAuto/twauto.py", line 156, in tweet 2023-06-28T19:33:59.001362+00:00 app[worker.1]: twAuto.driver.get("https://twitter.com/home") 2023-06-28T19:33:59.001362+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'get'
> > 
> > 
> > Can you try this fix: [#8 (comment)](https://github.com/EKOzkan/twAuto/issues/8#issuecomment-1604698617)
> > Version 4.4.3 solved the same error for that case. And if it does not solves your problem, try enabling the [debug mode](https://github.com/EKOzkan/twAuto#:~:text=debugMode%3D%20True/False), maybe that can gives us more details about your problem.
> 
> Actually, I enabled debug mode, there is nothing in the heroku logs And previously, when I used Android, this is the same error which occured but additionally got a debug log, which I showed you at the start. But this time there is no debug log in heroku logs.

This error happens when the Chrome driver could not be able to run or closed before twAuto`s actions. So you must fix that first. For that you must do the [steps that needed to run selenium in heroku platform](https://www.andressevilla.com/running-chromedriver-with-python-selenium-on-heroku/) first.

**Comment by pikachu62** [comment]
> > > > > Well if you are using a virtual machine as a server, or vps, or Linux based raspberry pi device as a server twAuto should work without any problems because I am also using it with my Raspberry Pi setup. For other uses tho, the environment you use, must be able to run Selenium/Chrome(or the browser that you prefer) instance, since twAuto literally based on it.
> > > > > Please don't hesitate to ask if you have any other problems or questions about the twAuto. Have a nice day.
> > > > 
> > > > 
> > > > Same error while doing it in server (used heroku this time)
> > > > tw.tweet(text=drunk,imgpath=new_path) 2023-06-28T19:33:59.001361+00:00 app[worker.1]: File "/usr/local/lib/python3.8/dist-packages/twAuto/twauto.py", line 156, in tweet 2023-06-28T19:33:59.001362+00:00 app[worker.1]: twAuto.driver.get("https://twitter.com/home") 2023-06-28T19:33:59.001362+00:00 app[worker.1]: AttributeError: 'NoneType' object has no attribute 'get'
> > > 
> > > 
> > > Can you try this fix: [#8 (comment)](https://github.com/EKOzkan/twAuto/issues/8#issuecomment-1604698617)
> > > Version 4.4.3 solved the same error for that case. And if it does not solves your problem, try enabling the [debug mode](https://github.com/EKOzkan/twAuto#:~:text=debugMode%3D%20True/False), maybe that can gives us more details about your problem.
> > 
> > 
> > Actually, I enabled debug mode, there is nothing in the heroku logs And previously, when I used Android, this is the same error which occured but additionally got a debug log, which I showed you at the start. But this time there is no debug log in heroku logs.
> 
> This error happens when the Chrome driver could not be able to run or closed before twAuto`s actions. So you must fix that first. For that you must do the [steps that needed to run selenium in heroku platform](https://www.andressevilla.com/running-chromedriver-with-python-selenium-on-heroku/) first.

Added buildpacks and tried again. No change.
